academics/assessments/urls.py
from django.urls import path

app_name = "assessments"

urlpatterns = []

academics/classes/urls.py
from django.urls import path

app_name = "classes"

urlpatterns = []

academics/marks/urls.py
from django.urls import path

app_name = "marks"

urlpatterns = []

academics/subjects/urls.py
from django.urls import path

app_name = "subjects"

urlpatterns = []

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    # path('list/', views.UserListView.as_view(), name='list'),
    # path('add/', views.UserCUView.as_view(), name='create'),
    # path('update/<int:pk>/', views.UserCUView.as_view(), name='update'),
    
    # path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # password change
    path('password_change/', views.LogoutView.as_view(), name='password_change'),
    path('password_change_done/', views.LogoutView.as_view(), name='password_change_done'),
    # password reset
    path('reset_password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

api/urls.py
from django.urls import path

app_name = "x_api"

urlpatterns = []

app/academics/urls.py
from django.urls import path
from . import views

app_name = "academics"

urlpatterns = [
    path('', views.ClassesAcademicsView.as_view(), name="classes"),
    path('<int:class_pk>/assessments/', views.ClassAssessmentsView.as_view(), name="assessments"),
]

app/management/urls.py
from django.urls import path

from . import views

app_name = "management"

urlpatterns = [
    path("", views.ManagementOverview.as_view(), name="overview"),
    path("terms/", views.ManagementTermsView.as_view(), name="terms"),
    path("classes/", views.ManagementClassesView.as_view(), name="classes"),
    path("subjects/", views.ManagementSubjectsView.as_view(), name="subjects"),
    path("subjects/<int:subject_pk>/", views.ManageSubjectView.as_view(), name="subject"),
    path("subjects/setup/", views.SubjectsSetupView.as_view(), name="subjects_setup"),
]

app/pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.LandingPageView.as_view(), name="landing"),
]

app/people/urls.py
from django.urls import path

from . import views

app_name = "people"

urlpatterns = [
    path("", views.PeopleOverviewView.as_view(), name="overview"),
    path("users/", views.PeopleUserView.as_view(), name="users"),
    path("students/", views.StudentsManagementView.as_view(), name="students"),
    path("students/new-enrollments/", views.StudentsNewEnrollmentsView.as_view(), name="new-students-enrollment"),
]

dotscholar/urls.py
from django.contrib import admin
from django.urls import path, include

from api.api import api_router

from .appsConfig import getAppUrls

import django_unicorn

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("unicorn/", include("django_unicorn.urls")),
    path('api/', api_router.urls),
]

urlpatterns += getAppUrls()

misc/onboarding/urls.py
from django.urls import path

from . import views

app_name = "onboarding"

urlpatterns = [
    path("", views.OnboardingView.as_view(), name="onboard"),
]

misc/staticpages/urls.py
from django.urls import path
from . import views

app_name = "staticpages"

urlpatterns = [
    path("", views.LandingPageView.as_view(), name="landing-page"),
]

people/parents/urls.py
from django.urls import path

app_name = "parents"

urlpatterns = []

people/staff/urls.py
from django.urls import path

app_name = "staff"

urlpatterns = []

people/students/urls.py
from django.urls import path

from . import views

app_name = "students"

urlpatterns = [
    path("", views.StudentListView.as_view(), name="student-list"),
]

people/teachers/urls.py
from django.urls import path

app_name = "teachers"

urlpatterns = []

schools/enrollment/urls.py
from django.urls import path

app_name = "enrollment"

urlpatterns = []

schools/schools/urls.py
from django.urls import path

app_name = "schools"

urlpatterns = []

schools/streams/urls.py
from django.urls import path

app_name = "streams"

urlpatterns = []

schools/terms/urls.py
from django.urls import path

app_name = "terms"

urlpatterns = []

subscriptions/tiers/urls.py
from django.urls import path

app_name = "tiers"

urlpatterns = []

app/pages/templates/pages/landing.html
<c-layout title="{{ request.user.get_school.short_name }} - Landing | DotScholar">

</c-layout>

dotscholar/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dot Scholar</title>
    <link rel="stylesheet" href="{% static 'compiled/index.css' %}">
</head>
<body class="h-screen bg-base-100">
    {% block content %}{% endblock %}
    <script src="{% static 'compiled/index.js' %}" defer></script>
</body>
</html>

dotscholar/templates/cotton/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,200..800;1,200..800&display=swap" rel="stylesheet">
</head>
<body class="h-screen bg-base-200 overflow-y-auto">
    {{ slot }}
    {% block content %}{% endblock %}
    <script src="{% static 'global.js' %}" defer></script>
    <script src="{% static 'index.js' %}" defer></script>
</body>
</html>

dotscholar/templates/cotton/components/header2.html
{% load static %}

<header
	id="navbar-sticky"
	class="fixed inset-x-0 top-0 z-50 show"
	x-data="{ 
    showMenu: false,
 }">
	<nav
		class="flex items-center justify-between p-4 lg:px-8 container mx-auto"
		aria-label="Global">
		<div class="flex lg:flex-1">
			<a href="{% url 'staticpages:landing-page' %}" title="Home link" class="-m-1.5 p-1.5">
				<span class="text-primary font-bold text-xl"> DotScholar </span>
				<!-- <img
                class="h-8 w-auto hidden"
                src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                alt=""
             /> -->
			</a>
		</div>
		<div class="hidden lg:flex lg:gap-x-4">
			<a href=""
				class="text-primary">
                Product
            </a>
			<a href=""
				class="text-primary">
                Solutions
            </a>
			<a href=""
				class="text-primary">
                Pricing
            </a>
			<a href=""
				class="text-primary">
                Get in Touch
            </a>
		</div>
		<div class="flex lg:flex-1 lg:justify-end">
			{% if request.user.isAuthenticated %}
			<a href="{% url 'pages:landing' %}"
				class="btn btn-neutral">
				Dashboard <span class="icon-arrow-right"></span>
			</a>
			{% else %}
			<a href="{% url 'accounts:login' %}"
				class="btn btn-neutral">
				Login <span class="icon-log-in"></span>
			</a>
			{% endif %}
		</div>
		<div class="lg:hidden">
			<button
				type="button"
				class="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700"
				@click="()=>{showMenu = !showMenu}">
				<span class="hidden">Open main menu</span>
				<svg
					class="h-6 w-6"
					fill="none"
					viewBox="0 0 24 24"
					stroke-width="1.5"
					stroke="currentColor"
					aria-hidden="true">
					<path
						stroke-linecap="round"
						stroke-linejoin="round"
						d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5"></path>
				</svg>
			</button>
		</div>
	</nav>
	<!-- Mobile menu, show/hide based on menu open state. -->
	<div
		class="lg:hidden fixed inset-0"
		x-show="showMenu"
		x-transition
		x-cloak
		role="dialog"
		aria-modal="true">
		<!-- Background backdrop, show/hide based on slide-over state. -->
		<div
			class="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 pt-6 pb-12 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10 grid">
			<div class="flex items-center justify-between">
				<a href="/" class="-m-1.5 p-1.5">
					<span class="text-primary font-bold text-3xl"> DotScholar </span>
					<!-- <img
                   class="h-8 w-auto"
                   src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=600"
                   alt=""
                /> -->
				</a>
				<button
					type="button"
					class="-m-2.5 rounded-md p-2.5 text-gray-700"
					@click="()=>{showMenu = !showMenu}">
					<span class="sr-only">Close menu</span>
					<svg
						class="h-6 w-6"
						fill="none"
						viewBox="0 0 24 24"
						stroke-width="1.5"
						stroke="currentColor"
						aria-hidden="true">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							d="M6 18L18 6M6 6l12 12"></path>
					</svg>
				</button>
			</div>
			<div class="mt-auto flow-root">
				<div class="-my-6 divide-y divide-gray-500/10">
					<div class="space-y-2 py-6 text-end">
						<a
							href="{% url 'staticpages:landing-page' %}"
							class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
							>Home</a
						>
						<a
							href=""
							class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
							>Services</a
						>
						<a
							href=""
							class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
							>Portfolio</a
						>
						<a
							href=""
							class="-mx-3 block rounded-lg px-3 py-2 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
							>Company</a
						>
						<a
							href=""
							class="-mx-3 block rounded-lg px-3 py-2.5 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50"
							>Book a meeting</a
						>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

dotscholar/templates/cotton/layout.html
{% load static unicorn %}

<c-base title="{{ title }}">
    <div class="flex h-screen">
        {% with user=request.user %} {% unicorn 'nav' user %} {% endwith %}
    
        <div class="flex-1 flex flex-col overflow-y-auto">{{ slot }}</div>
    </div>
</c-base>

dotscholar/templates/cotton/layout2.html
<c-base title="{{ title }}">
    <div class="flex flex-col">
        {% comment %}<!-- navbar -->{% endcomment %}
        <c-components.header2 />

        {{ slot }}
    </div>
</c-base>