academics/marks/urls.py
from django.urls import path

app_name = "marks"

urlpatterns = []

api/urls.py
from django.urls import path

app_name = "x_api"

urlpatterns = []

app/academics/urls.py
from django.urls import path
from . import views

app_name = "academics"

urlpatterns = [
    path('', views.ClassesAcademicsView.as_view(), name="classes"),
    path('<int:class_pk>/assessments/', views.ClassAssessmentsView.as_view(), name="assessments"),
]

dotscholar/urls.py
from django.contrib import admin
from django.urls import path, include

from api.api import api_router

from .appsConfig import getAppUrls

import django_unicorn

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("unicorn/", include("django_unicorn.urls")),
    path('api/', api_router.urls),
]

urlpatterns += getAppUrls()

academics/assessments/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from academics.classes.models import Class
from academics.subjects.models import Paper, Subject
from schools.terms.models import Term


class KINDS(models.TextChoices):
    CONTINUOUS = "CA", _("Continuous Assessment")
    EXAM = "EX", _("Examination")

    
class Assessment(models.Model):

    kind = models.CharField(_("Kind"), max_length=5, choices=KINDS.choices, default=KINDS.CONTINUOUS)
    order = models.PositiveSmallIntegerField(default=0)
    term = models.ForeignKey(Term, verbose_name=_("Term"), on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, verbose_name=_("Subject"), on_delete=models.CASCADE)
    cls = models.ForeignKey(Class, verbose_name=_("Class"), on_delete=models.CASCADE)

    date = models.DateField(_("Date"), null=True, blank=True)

    title = models.CharField(_("Title"), max_length=100)
    competency = models.TextField(_("Competency"), blank=True, null=True)
    papers = models.ManyToManyField(Paper, verbose_name=_("Papers"), blank=True)
    total_mark = models.PositiveSmallIntegerField(_("Total Mark"))

    class Meta:
        verbose_name = _("assessment")
        verbose_name_plural = _("assessments")
        unique_together = ("order", "term", "subject", "cls")

    def __str__(self):
        return self.title
    

academics/classes/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class LevelChoices(models.TextChoices):
    # PRIMARY = "P", _("Primary")
    ORDINARY = "O", _("Ordinary")
    ADVANCED = "A", _("Advanced")

class Class(models.Model):
    level = models.CharField(max_length=1, choices=LevelChoices.choices)
    number = models.CharField(max_length=1, choices=[(str(i), str(i)) for i in range(1, 8)], unique=True)
    
    class Meta:
        permissions = [
            ('can_manage_classes', 'Can manage classes'),
        ]

    def __str__(self):
        return f"S.{self.number}"
    
    def get_name(self):
        return f"S.{self.number}"
    
    def get_streams(self, school):
        return self.streams.filter(school=school)

academics/marks/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from academics.assessments.models import Assessment
from people.students.models import Student
from people.teachers.models import Teacher


class Mark(models.Model):

    assessment = models.ForeignKey(Assessment, verbose_name=_("Assessment"), on_delete=models.CASCADE)
    student = models.ForeignKey(Student, verbose_name=_("Student"), on_delete=models.CASCADE)
    score = models.PositiveSmallIntegerField(_("Score"))
    remarks = models.TextField(_("Remarks"), null=True, blank=True)
    teacher = models.ForeignKey(
        Teacher,
        verbose_name=_("Teacher"),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    class Meta:
        verbose_name = _("Mark")
        verbose_name_plural = _("Marks")
        unique_together = ("assessment", "student")

    def __str__(self):
        return self.name

academics/subjects/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from academics.classes.models import Class, LevelChoices
from schools.schools.models import School

# Create a subject manager with a method to get base subjects
class SubjectManager(models.Manager):
    def get_base(self):
        return self.filter(is_base=True)

    def get_default(self):
        return self.filter(is_default=True)
    
    def from_papers(self, papers):
        """
        Returns a QuerySet of Subjects, each annotated with a 'matched_papers'
        attribute containing only the Paper objects from the provided papers
        (list or QuerySet) that belong to that Subject.

        Args:
            papers (list or QuerySet): A list or QuerySet of Paper objects.

        Returns:
            QuerySet: A QuerySet of Subject objects, with 'matched_papers' attribute.
        """
        if isinstance(papers, list):
            papers_queryset = Paper.objects.filter(pk__in=[paper.pk for paper in papers])
        elif isinstance(papers, models.QuerySet) and papers.model == self.model._meta.get_field('papers').related_model:
            papers_queryset = papers
        else:
            raise TypeError("papers must be a list or QuerySet of Paper objects.")

        paper_pks = papers_queryset.values_list('pk', flat=True)

        filtered_papers_prefetch = models.Prefetch(
            'papers',
            queryset=papers_queryset.filter(pk__in=paper_pks),
            to_attr='allowed_papers'
        )

        return (
            self.filter(papers__pk__in=paper_pks)
            .distinct()
            .prefetch_related(filtered_papers_prefetch)
        )
    
    def get_base(self):
        return self.filter(is_base=True)
    
    def get_available_for_school(self, school: School):
        base_subjects = self.get_base()
        school_subjects = self.filter(school=school)
        # return both sets in one queryset
        return base_subjects | school_subjects
    
    def get_for_school(self, school: School):
        school_papers = school.paper_group.papers.all()
        return self.from_papers(school_papers)
    
    def get_from_papers(self, papers):
        subjects = []
        for paper in papers:
            subject = paper.subject
            if subject not in subjects:
                subjects.append(subject)
        
        for subject in subjects:
            subject_papers = papers.filter(subject=subject)
            subject.papers_matched = subject_papers

        return subjects
    

class Subject(models.Model):
    name = models.CharField(_("Name"), max_length=50)
    abbreviation = models.CharField(_("Abbreviation"), max_length=4, null=True, blank=True)
    code = models.CharField(_("Code"), max_length=4, unique=True)
    level = models.CharField(
        _("Level"),
        max_length=1,
        choices=LevelChoices.choices,
        null=True,
        blank=True,
    )
    classes = models.ManyToManyField(Class, verbose_name=_("Classes"), related_name="subjects", blank=True)
    category = models.ForeignKey(
        "Category",
        verbose_name=_("Category"),
        on_delete=models.CASCADE,
        related_name="subjects",
        null=True,
        blank=True,
    )
    is_base = models.BooleanField(_("Is Base"), default=False, help_text=_("Is this a base subject?"))
    is_default = models.BooleanField(_("Is Default"), default=False, help_text=_("Is this a default subject?"))
    school = models.ForeignKey(
        School,
        verbose_name=_("School"),
        on_delete=models.CASCADE,
        related_name="subjects",
        null=True,
        blank=True,
    )

    objects = SubjectManager()

    class Meta:
        verbose_name = _("Subject")
        verbose_name_plural = _("Subjects")
        
        permissions = [
            ("can_manage_all_subjects", "Can manage all subjects"),
        ]

    def __str__(self):
        return self.name


class Paper(models.Model):
    subject = models.ForeignKey(Subject, verbose_name=_("Subject"), on_delete=models.CASCADE, related_name="papers")
    number = models.CharField(_("Number"), max_length=2)
    name = models.CharField(_("Name"), max_length=100, null=True, blank=True)

    class Meta:
        verbose_name = _("Paper")
        verbose_name_plural = _("Papers")
        unique_together = (("subject", "number"),)

    def __str__(self):
        return self.get_name()
    
    def get_paper_code(self):
        return f"{self.subject.code}/{self.number}"
    
    def get_name(self):
        return self.name or ""
    
    def get_full_name(self):
        return self.name or f"Paper {self.number}"


class Category(models.Model):

    name = models.CharField(_("Name"), max_length=20, unique=True)

    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")

    def __str__(self):
        return self.name


class SchoolPaperAssignment(models.Model):
    school_papers_group = models.ForeignKey('SchoolPapersGroup', on_delete=models.CASCADE, related_name='paper_assignments')
    paper = models.ForeignKey('Paper', on_delete=models.CASCADE, related_name='school_assignments')
    is_compulsory = models.BooleanField(_('Is Compulsory'), default=False)

    class Meta:
        unique_together = (('school_papers_group', 'paper'),)
        verbose_name = _('School Paper Assignment')
        verbose_name_plural = _('School Paper Assignments')
        

    def __str__(self):
        return f"{self.paper} ({'Compulsory' if self.is_compulsory else 'Optional'}) - {self.get_level_display()}"

class SchoolPapersGroup(models.Model):
    school = models.OneToOneField(School, verbose_name=_("School"), on_delete=models.CASCADE, related_name="paper_group")
    papers = models.ManyToManyField(
        Paper,
        verbose_name=_("Papers"),
        related_name="school_papers_groups",
        blank=True,
        through='SchoolPaperAssignment',
        through_fields=('school_papers_group', 'paper'),
    )
    # classes = models.ManyToManyField(Class, verbose_name=_("Classes"), related_name="paper_groups")

    class Meta:
        verbose_name = _("SchoolPapersGroup")
        verbose_name_plural = _("SchoolPapersGroups")

    def __str__(self):
        return f"{self.school.name} Papers Group"

academics/assessments/forms.py
from django.forms import ModelForm

from . models import Assessment


class AssessmentForm(ModelForm):
    class Meta:
        model = Assessment
        fields = '__all__'

academics/marks/views.py
from django.shortcuts import render

# Create your views here.

app/academics/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View

from academics.assessments.forms import AssessmentForm
from academics.assessments.models import Assessment
from academics.classes.models import Class
from people.teachers.models import Teacher

# Create your views here.
class ClassSubjectsView(LoginRequiredMixin, View):
    def get(self, request, class_pk, *args, **kwargs):
        school = request.user.get_school()
        class_ = school.get_classes().get(pk=class_pk)
        
        template_name = 'academics/class-subjects.html'
        context = {
            "class": class_,
        }
        return render(request, template_name, context)


class ClassesAcademicsView(LoginRequiredMixin, View):
    template_name = "academics/classes.html"

    def get(self, request, *args, **kwargs):
        user = request.user
        school = user.get_school()
        classes = school.get_bare_classes()
        
        teacher_object = Teacher.objects.get(pk=user.pk)
        
        assignments = teacher_object.teaching_assignments.all()

        streams = []
        for assignment in assignments:
            stream = assignment.stream
            streams.append(stream)
        
        for cls in classes:
            cls.stream_assignments = set() # to hold the streams that are matched
            for stream in streams:
                if stream.current_class == cls:
                    cls.stream_assignments.add(stream)
                
                # indicate if the stream belongs to the logged in user
                stream.mine = (stream.class_teacher == request.user)
        
        context = {
            "classes": classes
        }
        return render(request, self.template_name, context)


class ClassAssessmentsView(LoginRequiredMixin, View):
    template_name = "academics/class-assessments.html"

    def redirect(self, class_pk):
        return redirect(reverse_lazy("academics:assessments", kwargs={"class_pk":class_pk}))
    
    def get(self, request, class_pk):
        school = request.user.get_school()
        cls = Class.objects.get(pk=class_pk)
        term = school.get_active_term()
        
        user = request.user
        teacher_object = Teacher.objects.get(pk=user.pk)
        assignments = teacher_object.teaching_assignments.all()
        
        all_papers = school.paper_group.papers.all()
        
        subjects = set()
        subject_ids = set()
        for assignment in assignments:
            subject = assignment.subject
            subject.school_papers = all_papers.filter(subject=subject)
            subjects.add(subject)
            subject_ids.add(subject.pk)
        
        
        assessments = Assessment.objects.filter(subject_id__in=subject_ids, term=term, cls=cls)
        
        form = AssessmentForm()
        
        context = {
            "subjects": subjects,
            "class": cls,
            "term": term,
            "assessments": assessments,
            "form": form
        }
        return render(request, self.template_name, context)
    
    def post(self, request, class_pk):
        school = request.user.get_school()
        cls = Class.objects.get(pk=class_pk)
        term = school.get_active_term()
        
        print(request.POST)
        
        form = AssessmentForm(request.POST)
        if form.is_valid():
            assessment = form.save()
            print(assessment)
            # assessment.term = term
            # assessment.cls = cls
            # assessment.save()
        else:
            print(form.errors)
            
        return self.redirect(class_pk)

app/academics/templates/academics/class-assessments.html
{% load widget_tweaks %}

<c-layout title="Classes Academics">
    <div class="px-4" x-data="clsacc_data">
        <div class="breadcrumbs text-sm">
            <ul>
                <li><a href="{% url 'academics:classes' %}">Classes</a></li>
                <li><a>{{ class.get_name }}</a></li>
                <li><a>Assessments</a></li>
            </ul>
        </div>

        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4" id="assessments">
            {% for assessment in assessments %}
            <div class="card bg-base-100" data-subject="{{ assessment.subject.pk }}"
                data-order="{{ assessment.order }}">
                <div class="card-body">
                    <div class="badge badge-sm badge-soft uppercase {% if assessment.kind == CA %}badge-neutral{% else %}badge-primary{% endif %}">
                        {{ assessment.get_kind_display }}
                    </div>
                    <div class="card-header">
                        <h2 class="card-title">{{ assessment.title }}</h2>

                        {% if assessment.date %}
                        <p class="text-xs opacity-60">{{ assessment.date }}</p>
                        {% endif %}
                    </div>

                    <p class="text-lg">{{ assessment.competency }}</p>

                    <ul class="list -mx-4">
                        <li class="list-row">
                            <div class="flex gap-6 justify-between">
                                <div>Subject:</div>
                            </div>
                            <div class="text-end list-col-grow">
                                <div>{{ assessment.subject.name }}</div>
                                <div>{{ assessment.subject.code }}</div>
                            </div>
                        </li>
                        <li class="list-row">
                            <div class="flex gap-6 justify-between">
                                <div>Max mark:</div>
                            </div>
                            <div class="text-end list-col-grow">
                                <div>{{ assessment.total_mark }}</div>
                            </div>
                        </li>
                        <li class="px-4 mt-4">
                            <div class="opacity-60 uppercase font-semibold">Papers Covered</div>
                        </li>
                        {% for paper in assessment.papers.all %}
                        <li class="list-row">
                            <div class="flex gap-6 justify-between">
                                <div>{{ paper.get_paper_code }}</div>
                            </div>
                            <div class="text-end list-col-grow">
                                <div>{{ paper.get_full_name }}</div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="flex gap-4 mt-4">
            <button class="btn btn-neutral" onclick="new_assessment_modal.showModal()">
                <span class="icon-plus"></span>
                Add an Assignment
            </button>
            <dialog id="new_assessment_modal" class="modal">
                <div class="modal-box relative @container">
                    <h3 class="text-lg font-bold text-center">Create an Assessment</h3>
                    <div class="steps w-full mb-8">
                        <button type="button" class="step text-sm" :class="{ 'step-primary': step >= 0 }"
                            @click="step = 0">
                            Basics
                        </button>
                        <button type="button" class="step text-sm" :class="{ 'step-primary': step >= 1 }"
                            @click="step = 1">
                            Advanced
                        </button>
                    </div>

                    <form method="post" x-ref="assignments_form" @submit="(event) => handleSubmit(event)" x-target="assessments">
                        {% csrf_token %}
                        <input type="hidden" name="cls" value="{{ class.pk }}" required />
                        <input type="hidden" name="term" value="{{ term.pk }}" required />
                        <input type="hidden" name="order" :value="next_order" required />

                        <div x-cloak x-show="step == 1">
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">
                                    <label for="{{ form.kind.id_for_label }}">{{ form.kind.label }} *</label>
                                </legend>
                                {{ form.kind|add_class:"select w-full" }}
                                <div class="label text-error">{{ form.kind.errors }}</div>
                                <p class="label">{{ form.kind.help_text }}</p>
                            </fieldset>

                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">
                                    <label for="{{ form.date.id_for_label }}">Date</label>
                                </legend>
                                {{ form.date|add_class:"input w-full"|attr:"type:date" }}
                                <div class="label text-error">{{ form.date.errors }}</div>
                                <p class="label">{{ form.date.help_text }}</p>
                            </fieldset>

                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">
                                    <label for="{{ form.subject.id_for_label }}">{{ form.subject.label }} *</label>
                                </legend>
                                <select name="subject" id="{{ form.subject.id_for_label }}" class="select w-full"
                                    @change="generateOptions($el)" required>
                                    <option value="">----</option>
                                    {% for subject in subjects %}
                                    <option value="{{ subject.pk }}">
                                        {{ subject.code }}: {{ subject.name }}
                                    </option>
                                    {% endfor %}
                                </select>
                                <div class="label text-error">{{ form.subject.errors }}</div>
                                <p class="label">{{ form.subject.help_text }}</p>
                            </fieldset>

                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">
                                    <label for="{{ form.papers.id_for_label }}">{{ form.papers.label }} *</label>
                                </legend>
                                <div class="grid" x-ref="paper_options">
                                    <label class="label">
                                        <input type="checkbox" class="checkbox" value="" />
                                        <span></span>
                                    </label>
                                </div>
                                <div class="label text-error">{{ form.papers.errors }}</div>
                                <p class="label">{{ form.papers.help_text }}</p>
                            </fieldset>

                            <div class="flex justify-end">
                                <button type="button" class="btn btn-ghost" @click="step--">
                                    <span class="icon-arrow-left"></span> Previous
                                </button>
                                <button class="btn btn-primary">
                                    Save <span class="icon-save"></span>
                                </button>
                            </div>
                        </div>

                        <div x-cloak x-show="step == 0">
                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">
                                    <label for="{{ form.title.id_for_label }}">{{ form.title.label }} *</label>
                                </legend>
                                {{ form.title|add_class:"input w-full" }}
                                <div class="label text-error">{{ form.title.errors }}</div>
                                <p class="label">{{ form.title.help_text }}</p>
                            </fieldset>

                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">
                                    <label for="{{ form.competency.id_for_label }}">{{ form.competency.label }}</label>
                                </legend>
                                {{ form.competency|add_class:"textarea w-full" }}
                                <div class="label text-error">{{ form.competency.errors }}</div>
                                <p class="label">{{ form.competency.help_text }}</p>
                            </fieldset>

                            <fieldset class="fieldset">
                                <legend class="fieldset-legend">
                                    <label for="{{ form.total_mark.id_for_label }}">{{ form.total_mark.label }}
                                        *</label>
                                </legend>
                                {{ form.total_mark|add_class:"input w-full" }}
                                <div class="label text-error">{{ form.total_mark.errors }}</div>
                                <p class="label">{{ form.total_mark.help_text }}</p>
                            </fieldset>

                            <div class="flex justify-end">
                                <button type="button" class="btn btn-ghost btn-sm" @click="step++">
                                    Next <span class="icon-arrow-right"></span>
                                </button>
                            </div>
                        </div>
                    </form>

                    <button type="button" class="btn btn-sm btn-circle absolute right-2 top-2" onclick="new_assessment_modal.close()">
                        <span class="icon-x"></span>
                    </button>
                </div>
            </dialog>
        </div>
    </div>

    <script>
        clsacc_data = {
            subjects: [// {% for subject in subjects %}
                {
                    id: Number("{{ subject.pk }}"),
                    code: "{{ subject.code }}",
                    name: "{{ subject.name }}",
                    papers: [// {% for paper in subject.school_papers %}
                        {
                            id: Number("{{ paper.pk }}"),
                            number: Number("{{ paper.number }}"),
                            name: "{{ paper.get_full_name }}"
                        },// {% endfor %}
                    ]
                },// {% endfor %}
            ],

            assessments: [],

            step: 0,
            next_order: null,

            generateOptions(element) {
                const value = element.value
                const subjects = this.subjects.filter(obj => obj.id == Number(value))

                const template = this.generatePaperOptions(subjects[0])

                const container = this.$refs.paper_options
                container.innerHTML = template

                this.setOrder(subjects[0])
            },
            generatePaperOptions(subject) {
                return subject.papers.map(paper => `<label class="label"><input type="checkbox" class="checkbox" value="${paper.id}" name="papers" /><span>${paper.number}: ${paper.name}</span></label>`)
            },

            setOrder(subject) {
                const assessments = this.assessments.filter(ass => ass.subject_id == subject.id)

                let order = 0
                assessments.forEach((ass) => {
                    if (Number(ass.order) > order) {
                        order = Number(ass.order)
                    }
                })

                this.next_order = order + 1
            },

            handleSubmit(event) {
                const checkboxes = this.$refs.assignments_form.querySelectorAll('input[name="papers"]');
                const checked = Array.from(checkboxes).some(cb => cb.checked);
                if (!checked) {
                    event.preventDefault();
                    alert("Please select at least one paper.");
                }
                console.log("Submit now")
                console.log(this.$refs.assignments_form)
                // this.$refs.assignments_form.requestSubmit()
            },

            getAssessments() {
                const cards = document.querySelectorAll('#assessments > *')

                cards.forEach((card) => {
                    const subject_id = card.getAttribute('data-subject')
                    const order = card.getAttribute('data-order')

                    this.assessments.push({ subject_id: subject_id, order: order })
                })
            },

            init() {
                this.getAssessments()
            }
        }
    </script>
</c-layout>

app/academics/templates/academics/class-subjects.html
<c-layout title="Classes Academics">
	<div class="px-3">
		<div class="breadcrumbs text-sm">
			<ul>
				<li><a href="{% url 'academics:classes' %}">Classes</a></li>
				<li><a>Subjects</a></li>
			</ul>
		</div>
	</div>
</c-layout>

app/academics/templates/academics/classes.html
<c-layout title="Classes Academics">
	<div class="px-3">
		<div class="breadcrumbs text-sm">
			<ul>
				<li><a>Classes</a></li>
			</ul>
		</div>
		<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
			{% for class in classes %}
			{% if class.stream_assignments %}
			<div class="card bg-base-100 rounded-box shadow-md">
				<div class="card-body">
					<div class="card-header flex items-center justify-between">
						<h2 class="card-header text-xl">{{ class.get_name }}</h2>
	
						<div class="card-actions">
							<a href="{% url 'academics:assessments' class.pk %}" class="btn btn-sm btn-ghost">
								Manage Assignments
								<span class="icon-arrow-right"></span>
							</a>
						</div>
					</div>

					<ul class="list -mx-4 mt-8">
						<li class="px-4 opacity-60 flex justify-between items-center">
							<span>Streams</span>
						</li>
						{% for stream in class.stream_assignments %}
						<li class="list-row">
							<div class="text-3xl font-thin opacity-30 tabular-nums">{{ forloop.counter }}</div>
							<div class="list-col-grow">
								<div class="font-semibold">{{ stream.name }}</div>
								<div class="opacity-60 uppercase text-xs">{{ stream.class_teacher.get_full_name }}</div>
							</div>
							<button class="btn btn-square btn-ghost">
								<svg
									class="size-[1.2em]"
									xmlns="http://www.w3.org/2000/svg"
									viewBox="0 0 24 24">
									<g
										stroke-linejoin="round"
										stroke-linecap="round"
										stroke-width="2"
										fill="none"
										stroke="currentColor">
										<path d="M6 3L20 12 6 21 6 3z"></path>
									</g>
								</svg>
							</button>
						</li>
						{% endfor %}
					</ul>
				</div>
			</div>
			{% endif %}
			{% endfor %}
		</div>
	</div>
</c-layout>