academics/assessments/urls.py
from django.urls import path

app_name = "assessments"

urlpatterns = []

academics/classes/urls.py
from django.urls import path

app_name = "classes"

urlpatterns = []

academics/marks/urls.py
from django.urls import path

app_name = "marks"

urlpatterns = []

academics/subjects/urls.py
from django.urls import path

app_name = "subjects"

urlpatterns = []

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    # path('list/', views.UserListView.as_view(), name='list'),
    # path('add/', views.UserCUView.as_view(), name='create'),
    # path('update/<int:pk>/', views.UserCUView.as_view(), name='update'),
    
    # path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    # password change
    path('password_change/', views.LogoutView.as_view(), name='password_change'),
    path('password_change_done/', views.LogoutView.as_view(), name='password_change_done'),
    # password reset
    path('reset_password/', views.PasswordResetView.as_view(), name='reset_password'),
    path('password_reset_done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
]

api/urls.py
from django.urls import path

app_name = "x_api"

urlpatterns = []

app/academics/urls.py
from django.urls import path
from . import views

app_name = "academics"

urlpatterns = [
    path('', views.ClassesAcademicsView.as_view(), name="classes"),
    path('<int:class_pk>/assessments/', views.ClassAssessmentsView.as_view(), name="assessments"),
]

app/management/urls.py
from django.urls import path

from . import views

app_name = "management"

urlpatterns = [
    path("", views.ManagementOverview.as_view(), name="overview"),
    path("terms/", views.ManagementTermsView.as_view(), name="terms"),
    path("classes/", views.ManagementClassesView.as_view(), name="classes"),
    path("subjects/", views.ManagementSubjectsView.as_view(), name="subjects"),
    path("subjects/<int:subject_pk>/", views.ManageSubjectView.as_view(), name="subject"),
    path("subjects/setup/", views.SubjectsSetupView.as_view(), name="subjects_setup"),
]

app/pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.LandingPageView.as_view(), name="landing"),
]

app/people/urls.py
from django.urls import path

from . import views

app_name = "people"

urlpatterns = [
    path("", views.PeopleOverviewView.as_view(), name="overview"),
    path("users/", views.PeopleUserView.as_view(), name="users"),
    path("students/", views.StudentsManagementView.as_view(), name="students"),
    path("students/new-enrollments/", views.StudentsNewEnrollmentsView.as_view(), name="new-students-enrollment"),
]

dotscholar/urls.py
from django.contrib import admin
from django.urls import path, include

from api.api import api_router

from .appsConfig import getAppUrls

import django_unicorn

urlpatterns = [
    path("admin/", admin.site.urls),
    
    path("unicorn/", include("django_unicorn.urls")),
    path('api/', api_router.urls),
]

urlpatterns += getAppUrls()

misc/onboarding/urls.py
from django.urls import path

from . import views

app_name = "onboarding"

urlpatterns = [
    path("", views.OnboardingView.as_view(), name="onboard"),
]

misc/staticpages/urls.py
from django.urls import path
from . import views

app_name = "staticpages"

urlpatterns = [
    path("", views.LandingPageView.as_view(), name="landing-page"),
]

people/parents/urls.py
from django.urls import path

app_name = "parents"

urlpatterns = []

people/staff/urls.py
from django.urls import path

app_name = "staff"

urlpatterns = []

people/students/urls.py
from django.urls import path

from . import views

app_name = "students"

urlpatterns = [
    path("", views.StudentListView.as_view(), name="student-list"),
]

people/teachers/urls.py
from django.urls import path

app_name = "teachers"

urlpatterns = []

schools/enrollment/urls.py
from django.urls import path

app_name = "enrollment"

urlpatterns = []

schools/schools/urls.py
from django.urls import path

app_name = "schools"

urlpatterns = []

schools/streams/urls.py
from django.urls import path

app_name = "streams"

urlpatterns = []

schools/terms/urls.py
from django.urls import path

app_name = "terms"

urlpatterns = []

subscriptions/tiers/urls.py
from django.urls import path

app_name = "tiers"

urlpatterns = []

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model, forms as auth_forms
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.template import loader
from django.urls import reverse_lazy
from django.utils.crypto import get_random_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.html import strip_tags



class PasswordResetForm(auth_forms.PasswordResetForm):
    pass

misc/staticpages/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.
class LandingPageView(View):
    def get(self, request):
        return render(request, 'staticpages/landing-page.html')

misc/staticpages/templates/unicorn/nav.html
<div
	x-data="{
    open: false,
    findActiveStatus(element, equal=false){
        
        let path = window.location.pathname;
        let url = element.getAttribute('href');

        const details = element.parentElement.parentElement.parentElement;

        if (path.startsWith(url) && !equal || equal && path === url) {
            {% comment %} set the details open attribute to true {% endcomment %}
            details.setAttribute('open', true)
            return true
        }
        
        {% comment %} set the details open attribute to false {% endcomment %}
        return false
    },
}"
	class="grid">
	<aside class="w-56 bg-white p-4 shadow flex flex-col">
		<h2 class="text-xl font-bold mb-6">{{ request.user.get_school.short_name }}</h2>
		<ul class="menu w-full p-0 -ml-2 flex-1 overflow-y-auto">
			{% for group in permitted_menu %}
			<li>
				<details>
					<summary class="font-semibold opacity-60">
						<span>{{ group.title }}</span>
					</summary>
					<ul>
						{% for link in group.links %}
						<li>
							<a
								href="{% url link.url %}"
								:class="findActiveStatus($el{% if link.equalsParam %}, true{% endif %}) ? 'text-primary bg-primary-content font-bold' : ''">
								{% if link.icon %}
								<i class="{{ link.icon }}"></i>
								{% else %}
								<i class="icon-dot"></i>
								{% endif %} {{ link.title }}
							</a>
						</li>
						{% endfor %}
					</ul>
				</details>
			</li>
			{% endfor %}
		</ul>
		<div>
			<div class="flex items-center space-x-2">
				<div class="dropdown dropdown-top">
					<button
						tabindex="0"
						aria-label="Account options button"
						class="avatar avatar-placeholder cursor-pointer">
						<div class="bg-neutral text-neutral-content w-8 rounded-full">
							<span class="text-xs">{{ request.user.get_initials }}</span>
						</div>
					</button>

					<div
						tabindex="0"
						aria-label="Account options"
						class="dropdown-content w-64 rounded-box bg-base-100 shadow-sm">
						<div class="p-4">
							<div class="grid place-content-center text-center mb-4">
								<h2 class="text-xl font-semibold">
									{{ request.user.get_full_name }}
								</h2>
								<p class="text-sm opacity-60">{{ request.user.email }}</p>
							</div>
							<form action="{% url 'accounts:logout' %}" method="post">
								{% csrf_token %}
								<button class="btn btn-soft btn-error w-full">
									Logout <span class="icon-log-out"></span>
								</button>
							</form>
						</div>
					</div>
				</div>
                
				<span class="font-medium text-sm">{{ request.user.get_short_name }}</span>
			</div>
		</div>
	</aside>
</div>